void get_all_substrings_seq(std::string, std::vector<std::string>);
void get_all_substrings_par(std::string, std::vector<std::string>);
void get_all_substrings_par_thread(std::string, std::vector<std::string>, int, int);
void find_palindromes_of_anagrams(std::string, std::vector<std::string>, int);
void find_palindromes_of_anagrams_par(std::vector<std::string>, std::vector<std::string>, int, int);
void recursive_palindrome_anagram_finder(std::string, std::string, std::string, std::vector<std::string>, int);
void kernel_substring_wrapper(char*, int);
void kernel_palindrome_wrapper(char**, int);
__global__ void get_all_substrings_cuda(char*, int);
__global__ void find_palindromes_of_anagrams_cuda(char**, int, char, int);
