void get_all_substrings_seq(std::string);
void get_all_substrings_par(std::string);
void get_all_substrings_par_thread(std::string, int, int);
void find_palindromes_of_anagrams(std::string, int);
void find_palindromes_of_anagrams_par(int, int);
void recursive_palindrome_anagram_finder(std::string, std::string, std::string, int);
void kernel_substring_wrapper(std::string);
void kernel_palindrome_wrapper(std::vector<std::string>);
__global__ void get_all_substrings_cuda(std::string);
__global__ void find_palindromes_of_anagrams_cuda(std::string, std::string, int);
